# zsh env

## Editor
export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

## Golang
export GOROOT="/usr/local/opt/go/libexec"
export GOPATH="$HOME/dev/golang"

## exports
export HOMEBREW_MAKE_JOBS=4

export SYS_PATH="/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
export USER_BIN="./local/bin"

## zplug
if [ -d /usr/local/opt/zplug ]; then
  export ZPLUG_HOME="/usr/local/opt/zplug"
fi

## anyenv
if [ -d $HOME/.anyenv ]; then
  export ANYENV="$HOME/.anyenv/bin"
  for D in `\ls $HOME/.anyenv/envs`
  do
    export ANYENV="$HOME/.anyenv/envs/$D/shims:$ANYENV"
  done
fi

export PATH="$ANYENV:$SYS_PATH:$USER_BIN:$ZPLUG_HOME:$GOROOT/bin:$GOPATH/bin"

