function source_file {
  if [ $# -lt 1 ];then
    echo "ERROR!!! source_file is called w/o an argument"
    return
  fi
  arg="$1"
  shift
  if [ -r "$arg" ]; then
    source "$arg"
  fi
}



# zplug init
if [ -d /usr/local/opt/zplug ]; then
  source_file $HOME/.config/zsh/zplug
fi

# Lines configured by zsh-newuser-install
HISTFILE=${HOME}/.zsh_history
HISTSIZE=50000
SAVEHIST=50000
setopt hist_ignore_all_dups hist_ignore_dups hist_expand hist_ignore_space
setopt extended_history share_history
setopt autocd beep extendedglob notify
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/Users/fagahhe2645/.zshrc'

autoload -Uz compinit; compinit
# End of lines added by compinstall


## anyenv
if [ -d $HOME/.anyenv ]; then
  eval "$(anyenv init -)"
fi


# alias
source_file $HOME/.config/zsh/zshalias
